# Generated by Django 3.1.12 on 2025-02-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20250226_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedwebsite',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
