# Generated by Django 3.2.13 on 2025-03-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_generatedwebsite_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedwebsite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
