# Generated by Django 3.2.13 on 2025-03-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_template_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
