# Generated by Django 3.2.13 on 2025-04-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_template_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
