# Generated by Django 3.2.13 on 2025-04-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_template_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('portfolio', 'Portfolio'), ('ecommerce', 'E-commerce'), ('blog', 'Blog'), ('landing', 'Landing Page'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
