# Generated by Django 4.2 on 2025-05-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20250414_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/template_images/'),
        ),
    ]
